# Generated by Django 2.2 on 2021-01-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usern',
        ),
        migrations.AddField(
            model_name='favourites',
            name='usern',
            field=models.CharField(default='xccgbcgv', max_length=120),
            preserve_default=False,
        ),
    ]
