# Generated by Django 2.2 on 2021-01-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210106_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='favourites',
            field=models.TextField(blank=True, null=True),
        ),
    ]
